apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 345619025376.dkr.ecr.us-west-2.amazonaws.com/movie-picture-backend-repo:${{ github.sha }}
          # # from primus learning
          imagePullPolicy: IfNotPresent   #Always
          ports:
            - containerPort: 5000
