apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: $REGISTRY/$REPOSITORY:$IMAGE_TAG
          # # from primus learning
          imagePullPolicy: IfNotPresent   #Always
          ports:
            - containerPort: 3000
