name:  movie-picture-workflow

# Triggers (manual & auto)
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

# env:
#   NODE_VERSION: "18"

jobs:
  Frontend-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # setting up node.js environment
      - name: Node.js environment setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # Installing dependencies
      - name: Install dependencies
        run: cd frontend && npm ci
  Frontend-Lint:
    needs: [Frontend-Setup]
    runs-on: ubuntu-latest
    steps:
      # Run the linter
      - name: Linting
        run: cd frontend && npm run lint
  Frontend-Test:
    needs: [Frontend-Setup]
    runs-on: ubuntu-latest
    steps:
      # Run the tests
      - name: Testing
        run: cd frontend && npm test
  Frontend-Build:
    needs: [Frontend-Lint, Frontend-Test]
    runs-on: ubuntu-latest
    steps:
      # Build the code
      - name: Code build
        run: cd frontend && npm run build
