name:  movie-picture-workflow

# Triggers (manual & auto)
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master



env:
  NODE_VERSION: 18

jobs:
  Frontend-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # setting up node.js environment
      - name: Node.js environment setup
        uses: actions/setup-node@v4
        with:
          node-version: $NODE_VERSION
      # Installing dependencies
      - name: Install dependencies
        run: cd frontend && npm ci
      # Run the linter
      - name: Linting
        run: cd frontend && npm run lint
  Frontend-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # setting up node.js environment
      - name: Node.js environment setup
        uses: actions/setup-node@v4
        with:
          node-version: $NODE_VERSION
      # Installing dependencies
      - name: Install dependencies
        run: cd frontend && npm ci
      # Run the tests
      - name: Testing
        run: cd frontend && npm test
  Frontend-Build:
    needs: [Frontend-Lint, Frontend-Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # setting up node.js environment
      - name: Node.js environment setup
        uses: actions/setup-node@v4
        with:
          node-version: $NODE_VERSION
      # Installing dependencies
      - name: Install dependencies
        run: cd frontend && npm ci
      # Run the tests
      - name: Building
        run: cd frontend && npm run build
